tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_cs_fixer:
            config: { level: psr2 } # or psr1 if you would just like to get fixes for PSR1
    php_code_sniffer:
            config:
                standard: "PSR2"

filter:
    excluded_paths:
        - 'tests/*'
        - 'fixtures/*'

build:
  environment:
      php:
        version: 5.5
      variables:
          APPLICATION_ENV: test
      hosts:
        samsoncms.local: '127.0.0.1'
      apache2:
        modules: ['rewrite']
        sites:
          samsoncms:
            web_root: 'vendor/samsoncms/cms/www/'
            host: 'samsoncms.local'

  dependencies:
    before:
       #- gunzip samsoncms.sql.gz
       - mysql -uroot -e "CREATE DATABASE samsoncms"
       # import mysql data needed for tests
       #- mysql -uroot samsoncms < samsoncms.sql
       - mysql -uroot -e "CREATE USER 'samsonos'@'localhost' IDENTIFIED BY 'AzUzrcVe4LJJre9f'";
       - mysql -uroot -e "GRANT ALL PRIVILEGES ON *.* TO 'samsonos'@'localhost' WITH GRANT OPTION";

  project_setup:
      before:
        - cd vendor/samsoncms/cms
        - composer install --prefer-dist --no-interaction
        - cd ../../../
        - command: 'phantomjs --webdriver=8643'
          background: true
        # run migrations
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local
        - wget http://samsoncms.local

